### ISSUE TITLE
Unable to connect to socketcluster server.

### ISSUE THREAD

**Issue by ricky1550** [abpopov/SocketCluster-ios-client#2]
its not giving any exception or crashing but also not getting connected to server.

**Comment by abpopov** [comment]
Hi!
Witch SC server version do you use?
Can you provide server log?

**Comment by nikhil-globant** [comment]
Hi abopov, even I'm not able to connect to server using this library & not receiving any response. 
We are using following client version SC version: "socketcluster": "~5.13.1", "socketcluster-client": "~5.5.0"

Is this library supported for v.5 & above?

**Comment by abpopov** [comment]
We using 5.5.0. I will update SC and check it. 

Do you have public SC server address - so I can check connection.

**Comment by abpopov** [comment]
and please check   path:  line in server.js

**Comment by nikhil-globant** [comment]
abpopov: Issue got fixed & SC is connecting & dispatching message. Actually, the host name generation was not  proper. I was proving host name with ws:// protocol at begginning & library is again appending ws:// at the beginning. Also port no was also appending at end of host name. Also, I've removed **?transport=websocket** from SCSocket class. This is how host name was generating:
ws://ws://abc.com:8001/socketcluster/:8001/?transport=websocket

Anyways, Thanks for your support!!!

**Comment by robinclark** [comment]
Hi, I'm running into the same issue. The client is not connecting to the server. I'm using the default server from socketcluster: http://socketcluster.io/#!/docs/getting-started

1) I setup a new project: socketcluster create myApp
2) I changed the default engine to 'ws' instead of 'uws'
3) ran server.js (on port 8000)

My ios client has following code to connect:
```
    override init() {
        super.init()
        connect()
    }

    func connect() {
        client = SCSocket.client()

        // TODO: test secure connection
        client!.initWithHost(192.168.0.5, onPort: 8000,
                             securely: false)
        client!.delegate = self
        client!.setRestoreChannels(true)
        client!.connect()
        
        debugPrint("trying to connect")
    }
```
I can see that the websocket has the correct url: "ws://192.168.0.5:8000/?transport=websocket". Is there something I'm missing? Any ideas?

Thanks
